Sample Content for Offcourse
============================
Author Name <yeehaa@offcourse.io§>
v1.0, 2015-30-11

== Themes

[square]
- Coding
- Art
- Technology
- Human Body
- Nature
- Language
- Urbanism
- Data
- Architecture
- Food
- Tools
- Transportation

+++*+++ JH: I still have doubts whether or not adding themes is a good idea...
It's okay for demo purposes, but needs to be reevaluated before moving on.

== Sample Theme

Theme: Coding

.Courses:
[square]
- Coding the Humanities
- From Object to Data
- The Web as Publication Platform
- Visualizing Data
- Putting the Big Back in Data
- Augmenting Masterpieces
- The Human Body as Big Data
- The City as Interface
- HTML for Humanists
- Rocking Recommendation Systems
- Git for Research
- Open Sourcing the Academy


== Sample Course

https://github.com/OffCourse/content-for-lifely/blob/master/sample-course.yaml

== Glossary

https://github.com/OffCourse/glossary


== Styling

All Donald's styling instructions and mockups can be found here:

https://github.com/OffCourse/styleguide

Our fonts (Nitti and Nitti Grotesk) can be downloaded from our dev git repo.

https://github.com/yeehaa123/offcourse-fullstack/tree/master/resources/public/fonts

Beware not to use them elsewhere though. They are licensed.
